import GreatCursor from "@/Client/Main-page/GreatCursor";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GreatCursor>
        {children}
      </GreatCursor>
    </html>
  );
}
